name: install-intel-graphics
description: Download and unpack Intel graphics drivers
inputs:
  GPU:
    description: "Install for PVC or BMG gpu"
    type: string
  IGC:
    description: "Use ROLLING or STAGING release"
    type: string

runs:
  using: "composite"
  steps:
    - name: Install Intel graphics drivers
      if: inputs.IGC == 'ROLLING'
      shell: bash
      run: |
        shopt -s expand_aliases
        which sudo || alias sudo=""
        if [[ "${{ inputs.GPU }}" == "BMG" || "${{ inputs.GPU }}" == "PVC" ]]; then
          sudo add-apt-repository ppa:kobuk-team/intel-graphics
          sudo apt update
        else
          # LTS PVC drivers
          # . /etc/os-release
          # wget https://repositories.intel.com/gpu/ubuntu/dists/${VERSION_CODENAME}/intel-gpu-ubuntu-${VERSION_CODENAME}.run
          # chmod +x intel-gpu-ubuntu-${VERSION_CODENAME}.run
          # sudo ./intel-gpu-ubuntu-${VERSION_CODENAME}.run
          # sudo apt install -y \
          #   intel-media-va-driver-non-free libmfx-gen1 libvpl2 \
          #   libegl-mesa0 libegl1-mesa-dev libgl1-mesa-dev  \
          #   libgles2-mesa-dev libigdgmm12 libxatracker2 mesa-va-drivers \
          #   mesa-vdpau-drivers mesa-vulkan-drivers va-driver-all vainfo \
          #   libigc-dev intel-igc-cm libigdfcl-dev libigfxcmrt-dev libze-dev hwinfo
          exit 1
        fi
        sudo apt-get install -y libze-intel-gpu1 libze-dev intel-metrics-discovery \
          intel-opencl-icd ocl-icd-opencl-dev clinfo intel-gsc intel-ocloc g++
        dpkg -l | grep libhwloc15 > /dev/null || sudo apt install -y libhwloc15
    - name: Install Intel graphics drivers
      if: inputs.IGC == 'STAGING'
      shell: bash
      run: |
        shopt -s expand_aliases
        which sudo || alias sudo=""
        if [[ "${{ inputs.GPU }}" == "BMG" ]]; then
          sudo rm -f /etc/apt/sources.list.d/kobuk-team-ubuntu-intel-graphics-*
          sudo add-apt-repository ppa:kobuk-team/intel-graphics-staging
          sudo apt update
          sudo apt-get install -y libze-intel-gpu1 libze-dev intel-metrics-discovery \
            intel-opencl-icd ocl-icd-opencl-dev clinfo intel-gsc intel-ocloc g++
          dpkg -l | grep libhwloc15 > /dev/null || sudo apt install -y libhwloc15
        else
          exit 1
        fi

    - name: Install Intel graphics drivers
      if: inputs.IGC == 'DOWNGRADE'
      shell: bash
      run: |
        shopt -s expand_aliases
        which sudo || alias sudo=""
        sudo rm -f /etc/apt/sources.list.d/kobuk-team-ubuntu-intel-graphics-*
        sudo rm -rf neo
        mkdir neo || true
        cd neo
        wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.20.3/intel-igc-core-2_2.20.3+19972_amd64.deb
        wget https://github.com/intel/intel-graphics-compiler/releases/download/v2.20.3/intel-igc-opencl-2_2.20.3+19972_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/intel-ocloc-dbgsym_25.40.35563.4-0_amd64.ddeb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/intel-ocloc_25.40.35563.4-0_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/intel-opencl-icd-dbgsym_25.40.35563.4-0_amd64.ddeb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/intel-opencl-icd_25.40.35563.4-0_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/libigdgmm12_22.8.2_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/libze-intel-gpu1-dbgsym_25.40.35563.4-0_amd64.ddeb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/libze-intel-gpu1_25.40.35563.4-0_amd64.deb
        wget https://github.com/intel/compute-runtime/releases/download/25.40.35563.4/ww40.sum
        sha256sum -c ww40.sum
        sudo dpkg -i *.deb
        cd ..
        sudo apt update
        sudo apt install -y libze-dev ocl-icd-opencl-dev intel-metrics-discovery \
        clinfo intel-gsc g++
        dpkg -l | grep libhwloc15 > /dev/null || sudo apt install -y libhwloc15
