#!/usr/bin/env python3
"""Generate per-batch benchmarks_sycl.hpp."""
import re, argparse, shutil
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
FULL = REPO / "benchmarks/gemm/benchmarks_sycl.hpp"
CACHE = REPO / "benchmarks/gemm/benchmarks_sycl.hpp.cache"

# Tile sizes generated by BMG_DECLARE_EXPANDED_GEMM_TILES
EXPANDED_TILES_SG8x4 = {
    (64,64,32),(64,64,64),(64,128,32),(64,128,64),(64,256,32),(64,256,64),
    (128,64,32),(128,64,64),(128,128,32),(128,128,64),(128,256,32),(128,256,64),(128,256,16),(128,512,32),
    (256,64,32),(256,64,64),(256,128,32),(256,128,64),(256,192,64),(256,256,32),(256,256,64),(256,256,16),
    (512,64,32),(512,64,64),(512,128,32),(512,128,64),(512,256,32),(512,256,64),
}

# Tile sizes generated by BMG_DECLARE_EXPANDED_STREAMK_TILES
EXPANDED_STREAMK_TILES = {
    (64,64,32),(64,64,64),(64,128,64),(64,256,64),
    (128,64,32),(128,64,64),(128,128,64),(128,256,64),
    (256,64,32),(256,64,64),(256,128,64),(256,256,64),
    (512,64,32),(512,64,64),(512,128,64),(512,256,64),
}

def full_text():
    # Always re-read from canonical source to avoid stale cache
    if CACHE.exists():
        CACHE.unlink()
    shutil.copy2(FULL, CACHE)
    with open(CACHE) as f: return f.read()

def classify(name):
    m = re.match(r'^(\w+)_GemmExhaustive_(\d+)x(\d+)x(\d+)_SG(\d+)x(\d+)_ST(\d+)$', name)
    if m: return 'ge', m.group(1), {'M':m.group(2),'N':m.group(3),'K':m.group(4),'SGM':m.group(5),'SGN':m.group(6),'ST':m.group(7)}
    m = re.match(r'^(\w+)_Gemm_(\d+)x(\d+)x(\d+)_SG(\d+)x(\d+)$', name)
    if m: return 'gs', m.group(1), {'M':m.group(2),'N':m.group(3),'K':m.group(4),'SGM':m.group(5),'SGN':m.group(6)}
    m = re.match(r'^(\w+)_(StreamK|DataParallel|SplitK)_(\d+)x(\d+)x(\d+)$', name)
    if m: return 'sk', m.group(1), {'M':m.group(3),'N':m.group(4),'K':m.group(5)}
    return 'hw', name, {}

def cfg_atom(pfx):
    if 'RRR' in pfx: return 'Gemm_Bench_BF16FP32_RRR', 'MMAAtom'
    if 'FP16FP16FP32' in pfx or pfx.startswith('BmgGemmFP16'): return 'Gemm_Bench_F16FP32_RCR', 'MMAAtomF16'
    if 'F16F16F16' in pfx: return 'Gemm_Bench_F16F16F16_RCR', 'MMAAtomF16AccF16'
    if 'TF32' in pfx: return 'Gemm_Bench_TF32FP32_RCR', 'MMAAtomTF32'
    return 'Gemm_Bench_BF16FP32_RCR', 'MMAAtom'

def covered(name, text):
    """Check if kernel type is already defined in full HPP."""
    # Direct using declaration
    if re.search(rf'using\s+{re.escape(name)}\s*=', text): return True
    t, pfx, p = classify(name)
    if t == 'gs' and p['SGM'] == '8' and p['SGN'] == '4':
        sz = (int(p['M']), int(p['N']), int(p['K']))
        if sz in EXPANDED_TILES_SG8x4: return True
    # StreamK/DP/SplitK from BMG_DECLARE_EXPANDED_STREAMK_TILES
    if t == 'sk':
        sz = (int(p['M']), int(p['N']), int(p['K']))
        if sz in EXPANDED_STREAMK_TILES: return True
    return False

def gen_mini(kernels, output):
    text = full_text()
    
    declares = []
    registers = []
    for k in sorted(set(kernels)):
        t, pfx, p = classify(k)
        if t == 'hw' or t == 'gs' or covered(k, text): continue
        c, a = cfg_atom(pfx)
        if t == 'ge':
            declares.append(f'BMG_DECLARE_EXHAUSTIVE_GEMM_TILE_STAGE({pfx}, {c}, {a}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]}, {p["ST"]})')
        else:
            # Generate StreamK/DP/SplitK type directly via GemmConfiguration
            # Bypasses BMG_DECLARE_STREAMK_TILE + Gemm_Bench_*_StreamK templates
            if not covered(k, text):
                M, N, K = p["M"], p["N"], p["K"]
                sn = f'{pfx}_StreamK_TileShape_{M}_{N}_{K}'
                tn = f'{pfx}_StreamK_Tile_{M}_{N}_{K}'
                if 'DataParallel' in k: sched = 'GemmDataParallel'
                elif 'SplitK' in k: sched = 'GemmSplitK'
                else: sched = 'GemmStreamK'
                declares.append(f'using {sn} = Shape<_{M}, _{N}, _{K}>;')
                declares.append(f'using {tn} = TiledMMAHelper<MMAAtom, Layout<{sn}>, Layout<Shape<_8, _4, _1>, Stride<_4, _1, _0>>>::TiledMMA;')
                declares.append(f'using {k} = cutlass::gemm::device::GemmConfiguration<cutlass::arch::IntelXe, cutlass::bfloat16_t, cutlass::layout::RowMajor, cutlass::bfloat16_t, cutlass::layout::ColumnMajor, float, cutlass::layout::RowMajor, float, {sn}, Scheduler::{sched}, {tn}, void, void, cutlass::epilogue::fusion::LinearCombination<float,float,float,float,cutlass::FloatRoundStyle::round_to_nearest>, 2, cutlass::gemm::KernelXeCooperative>;')
                declares.append(f'CUTLASS_CREATE_GEMM_BENCHMARK({k});')
            registers.append(f'  CUTLASS_BENCHMARK({k});')
    
    for k in sorted(set(kernels)):
        t, pfx, p = classify(k)
        if t == 'hw':
            registers.append(f'  CUTLASS_BENCHMARK({k});')
        elif t == 'gs':
            registers.append(f'  BMG_REGISTER_GEMM_TILE_SG({pfx}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]})')
        elif t == 'ge':
            registers.append(f'  BMG_REGISTER_EXHAUSTIVE_GEMM_TILE_STAGE({pfx}, {p["M"]}, {p["N"]}, {p["K"]}, {p["SGM"]}, {p["SGN"]}, {p["ST"]})')
        # sk already handled above
    
    m = re.search(r'static void register_gemm_benchmarks', text)
    pos = m.start() if m else len(text)
    new_text = text[:pos]
    if declares:
        new_text += '\n// Batch kernel declarations\n' + '\n'.join(declares) + '\n'
    new_text += '\nstatic void register_gemm_benchmarks() {\n'
    new_text += '\n'.join(registers) + '\n}\n'
    
    with open(output, 'w') as f: f.write(new_text)
    shutil.copy2(output, FULL)
    print(f"Generated: {len(kernels)} k, {len(declares)} d, {len(registers)} r")

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--manifest", required=True); p.add_argument("--output", required=True)
    a = p.parse_args()
    with open(a.manifest) as f: k = [l.strip() for l in f if l.strip()]
    gen_mini(k, a.output)
