name: "TorchInductor CUTLASS UTs"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {}

jobs:
  run-cutlass-test:
    name: Run TorchInductor CUTLASS test
    runs-on: bmg
    timeout-minutes: 120
  
    steps:
      - name: Checkout sycl-tla repo
        uses: actions/checkout@v4

      - name: Install Python venv package
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv

      - name: Install Intel graphics drivers
        uses: ./.github/actions/install-intel-graphics
        with:
          GPU: 'BMG'
          IGC: 'ROLLING'

      - name: Install DPC++
        id: install_dpcpp
        uses: ./.github/actions/install-dpcpp
        with:
          DPCPP_RELEASE: RELEASE
          DPCPP_PATH: ~/dpcpp

      - name: Setup virtual environment
        shell: bash
        run: |
          python3 -m venv ~/.venv
          source ~/.venv/bin/activate
          . setvars.sh
          env >> $GITHUB_ENV

      - name: Install nightly PyTorch
        shell: bash
        run: |
          source ~/.venv/bin/activate
          pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/xpu

      - name: Print IGC2 version
        shell: bash
        run: |
          dpkg-query --show libigc2

      - name: Print PyTorch package version
        shell: bash
        run: |
          pip list | grep -i torch

      - name: Clone PyTorch fork
        shell: bash
        run: |
          cd ${{ runner.temp }}
          git clone https://github.com/pytorch/pytorch.git -b origin/nightly

      - name: Run TorchInductor CUTLASS test
        shell: bash
        run: |
          source ~/.venv/bin/activate
          export CUTLASS_USE_SYCL=1
          export ONEAPI_DEVICE_SELECTOR=level_zero:gpu
          export TORCHINDUCTOR_CUTLASS_DIR="${GITHUB_WORKSPACE}"
          cd ${{ runner.temp }}
          python test/inductor/test_cutlass_backend.py -v

      - name: Run TorchInductor EVT test
        shell: bash
        run: |
          source ~/.venv/bin/activate
          export TORCHINDUCTOR_CUTLASS_DIR="${GITHUB_WORKSPACE}"
          mkdir ${GITHUB_WORKSPACE}/logs/
          cd ~/pytorch/pytorch-inductor-xpu
          python test/inductor/test_cutlass_evt.py -v 2>&1 | tee ${GITHUB_WORKSPACE}/logs/cutlass_inductor_evt.log

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-artifacts
          path: logs/

      - name: Cleanup PyTorch repo and wheel
        if: always()
        shell: bash
        run: |
          rm -rf ${{ runner.temp }}/pytorch

